_commit: 4089ffe
_src_path: gh:bswck/skeleton
author_username: bswck
docs: true
docs_slug: modern-types
email_address: bswck.dev@gmail.com
github_username: bswck
license_name: MIT
org_full_name: Bartosz Sławecki
package_name: __modern_types__
project_description: '`__modern_types__` aims to provide [PEP 585](https://peps.python.org/pep-0585/)
    + [PEP 604](https://peps.python.org/pep-0604/) backports for Python <=3.10 deferred
    type evaluation backward compatibility. '
publish_on_pypi: true
pypi_project_description: PEP 585 + PEP 604 backports.
pypi_project_name: modern-types
python_version: '3.8'
repo_name: modern_types
test_suite: true
use_precommit: true
visibility: public
